export type DocumentPlatformErrorCode =
  | "TRUSTED_CONTEXT_INVALID"
  | "DOCUMENT_ALREADY_EXISTS"
  | "DOCUMENT_NOT_ACCESSIBLE"
  | "DOCUMENT_NOT_FOUND"
  | "DOCUMENT_ARCHIVED"
  | "DOCUMENT_VERSION_MISMATCH"
  | "DOCUMENT_VERSION_EXISTS"
  | "DOCUMENT_VERSION_NOT_FOUND"
  | "DOCUMENT_UNAVAILABLE"
  | "CONVERSATION_NOT_ACCESSIBLE"
  | "CONVERSATION_DOCUMENT_NOT_FOUND"
  | "MESSAGE_NOT_ACCESSIBLE"
  | "MESSAGE_SELECTION_CONFLICT"
  | "SELECTION_INPUT_INVALID"
  | "PROJECT_NOT_ACCESSIBLE"
  | "DOCUMENT_OBJECT_MISSING"
  | "DOCUMENT_OBJECT_METADATA_MISMATCH"
  | "DOCUMENT_INPUT_INVALID"
  | "DOCUMENT_VERSION_INVALID"
  | "DOCUMENT_VERSION_METADATA_MISMATCH"
  | "DOCUMENT_STATUS_TRANSITION_INVALID"
  | "UPLOAD_INTENT_NOT_FOUND"
  | "UPLOAD_INTENT_EXPIRED"
  | "UPLOAD_INTENT_INVALID"
  | "STORAGE_OBJECT_EXISTS"
  | "STORAGE_PRECONDITION_FAILED"
  | "STORAGE_METADATA_INVALID"
  | "STORAGE_CAPABILITY_UNSUPPORTED"
  | "JOB_IDEMPOTENCY_CONFLICT"
  | "JOB_NOT_FOUND"
  | "JOB_INPUT_INVALID"
  | "JOB_STATUS_TRANSITION_INVALID"
  | "JOB_LEASE_INVALID"
  | "WORKER_ENVELOPE_INVALID"
  | "WORKER_ENVELOPE_MISMATCH"
  | "QUEUE_JOB_NOT_FOUND"
  | "QUEUE_LEASE_EXPIRED";

export class DocumentPlatformError extends Error {
  readonly code: DocumentPlatformErrorCode;

  constructor(code: DocumentPlatformErrorCode, message: string = code) {
    super(message);
    this.name = "DocumentPlatformError";
    this.code = code;
  }
}
